### PR TITLE
WIP: Upgrade away from CGLib to be usable w/ Java17

### PR DESCRIPTION
**Pull request by ccjmne**
- Dropped CGLib in favour of ByteBuddy
- Converted line endings to Unix using `dos2unix`

There's an issue with `ProxyUtils`, I just can't get it to work.

This overall probably isn't the right solution for us, but I'll just back up what I've been doing so far just in case we decide to come back to it.

### CODE REVIEW

**Comment by ccjmne** [comment]
Oh, this probably shouldn't target `master` either. Well, it's really only for posterity, I don't intend to have this merged at all :)

**Comment by mweirauch** [comment]
@ccjmne perhaps a switch to Wicketstuffs lazymodel module might be worth a try? Wicketstuff is usually up-to-date with the major wicket versions.
I just quickly looked. No guarantees this is what might be a replacement: https://github.com/wicketstuff/core/blob/master/wicketstuff-lazymodel/src/main/java/org/wicketstuff/lazymodel/LazyModel.java

**Comment by uweschaefer** [comment]
yeah, sorry. Sven did a good Job there and i am off Wicket for years (unfortunately).

**Comment by uweschaefer** [comment]
thx @mweirauch for jumping in.

**Pull request closed without merging**
