### PR TITLE
change pom version and improve gitgnore

### PR DESCRIPTION
**Pull request by reiern70**
don not merge just yet... testing with our application.

### CODE REVIEW

**Comment by uweschaefer** [comment]
thanks for contributing.

i don't quite get the version shift from SEMVER to 7.2. what is the reasoning behind it?

**Comment by reiern70** [comment]
Please... put any number you deem convenient. I just thought it might be
good to be aligned with wicket version 7.2.0.

Also: do you think it might be convenient to move it to wicket-stuff? So,
that its periodically released?

On Sat, Mar 19, 2016 at 1:02 PM, Uwe Schaefer <notifications@github.com>
wrote:

> thanks for contributing.
>
> i don't quite get the version shift from SEMVER to 7.2. what is the
> reasoning behind it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/uweschaefer/wicket-modelfactory/pull/7#issuecomment-198691554>
>



-- 
Regards - Ernesto Reinaldo Barreiro

**Comment by uweschaefer** [comment]
i'd rather try to keep this separate from wicketstuff and release it as fine-grained as possible.
truth is, for wicket8 this will be no longer useful – to heavyweight so that i'll redo this anyway.

**Comment by uweschaefer** [comment]
do you work on that pull req, shift the deps to wicket 7 and make the necessary changes? i am asking, because i might find some time next week, but i would not want to interfere with your work.
maybe i can help via review/comment on the changes you did already? please let me know.

**Comment by reiern70** [comment]
Hi,

No changes where needed to get our application working. All test units
where passing... My changes where just cosmetic. Please feel free to do
whatever you need necessary. I will then retest your changes against our
application. Thanks again!

On Sun, Mar 20, 2016 at 6:31 PM, Uwe Schaefer <notifications@github.com>
wrote:

> do you work on that pull req, shift the deps to wicket 7 and make the
> necessary changes? i am asking, because i might find some time next week,
> but i would not want to interfere with your work.
> maybe i can help via review/comment on the changes you did already? please
> let me know.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/uweschaefer/wicket-modelfactory/pull/7#issuecomment-198969499>
>



-- 
Regards - Ernesto Reinaldo Barreiro

**Comment by reiern70** [comment]
Hi,

Do you have time to work on this? Release a new version?

**Comment by uweschaefer** [comment]
can do, but just for the .gitignore cleanup? i wanted to improve a few minor things to make the static cone analysis a little happier. would it be good to have a minor version before and after?

**Comment by reiern70** [comment]
Ok. Just push something to maven and I will test it... Or tell me what to
fetch and I can test it locally... Thanks!

On Wed, Apr 6, 2016 at 3:56 PM, Uwe Schaefer <notifications@github.com>
wrote:

> Merged #7 <https://github.com/uweschaefer/wicket-modelfactory/pull/7>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/uweschaefer/wicket-modelfactory/pull/7#event-616843138>
>



-- 
Regards - Ernesto Reinaldo Barreiro

**Comment by uweschaefer** [comment]
release some minor versions to maven central yesterday: [wicket-modelfactory at maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.wicketeer%22%20AND%20a%3A%22wicket-modelfactory%22)

Please take a look at the tags/commit history here, to find out - which one you want.
My guess is, it should be irrelevant which one you use, so 0.9.15 would be fine.

In case you'd find any regression or have anything to add / suggest, feel free to open new issues.

thanks for contributing / testing - appreciated.

**Comment by reiern70** [comment]
Thanks to you fro the support!

On Thu, Apr 7, 2016 at 7:16 PM, Uwe Schaefer <notifications@github.com>
wrote:

> release some minor versions to maven central yesterday: wicket-modelfactory
> at maven central
> <http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.wicketeer%22%20AND%20a%3A%22wicket-modelfactory%22>
>
> Please take a look at the tags/commit history here, to find out - which
> one you want.
> My guess is, it should be irrelevant which one you use, so 0.9.15 would be
> fine.
>
> In case you'd find any regression or have anything to add / suggest, feel
> free to open new issues.
>
> thanks for contributing / testing - appreciated.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/uweschaefer/wicket-modelfactory/pull/7#issuecomment-207002020>
>



-- 
Regards - Ernesto Reinaldo Barreiro

**Pull request merged**
